language: node_js

node_js:
 - "6"
 - "8"

cache:
  directories:
    - "node_modules"

before_script:
  - npm install
  - npm install coveralls

script: npm test

after_success:
  - npm run istanbul cover _mocha --timeout 5000 --exit -- --report lcovonly && coveralls